### ISSUE TITLE
Impossible to redefine macro with value

### ISSUE THREAD

**Issue by arkrost** [seanpringle/reforth#1]
Hi!

I can't deal with the following problem.  Let's define dummy macro

```
 macro : foo 2 + . cr ; normal
 3 foo \ outputs 5
```

Then try to define normal word:

```
  : foo 5 + . cr ; 
  3 foo \ outputs 5, but expected 8
```

From my point of view, macros and words have different namespaces. If it's expected behavior, please point idiomatic way to change it, i.e. make single scope for macros and words.

**Comment by seanpringle** [comment]
Reforth uses the dual wordlist approach, similar to cmForth. Macro word list holds immediate words and is always searched first. To change the behaviour you would need to modify EVALUATE.

https://github.com/seanpringle/reforth/blob/master/reforth.c#L2723

**Comment by arkrost** [comment]
Is it possible to remove word from macro wordlist?

**Comment by arkrost** [comment]
Thanks you!
